title: LOD on GitHub Workshop
author: Wout Dillen
copyright: "2026–present"

html:
  extra_footer: |
    Content licensed under
    <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">
      CC BY 4.0
    </a>.
    <br>
    Last updated: {{LAST_UPDATED}}
    <br>
    <a href="{{GITHUB_URL}}" target="_blank">
      Find on GitHub
    </a>

exclude_patterns:
  - .venv/**
  - _build/**
  - "**/.ipynb_checkpoints"