title: Visualize Your Linked Open Data
author: Wout Dillen
copyright: "2026–present"

html:
  extra_footer: |
    Content licensed under
    https://creativecommons.org/licenses/by/4.0/
      CC BY 4.0
    </a>.

exclude_patterns:
  - .venv/**
  - _build/**
  - "**/.ipynb_checkpoints"